### ISSUE TITLE
The sheet only presents from the last view defined with an activity

### ISSUE THREAD

**Issue by elitecoder** [SwiftUI-Plus/ActivityView#1]
## General Information
 - Platform/OS version: 
iPad OS 14.7.1
 
 - IDE version:
Xcode 12.5.1
 
 - Devices: 
iPad Pro
 

## Describe the bug
I am creating 2 Buttons in an HStack and attaching ActivityView to both of them. But regardless of which button I press, ActivityView instances show up only on the 2nd button.
If I add more buttons, they show up on the last button created.

## Steps to reproduce
Try the following code on iPad (I was using Landscape mode)
```
@State private var item: ActivityItem?

var body: some View {
        HStack {
            Button {
                item = ActivityItem(
                    items: "Button 1: This will be shared"
                )
            } label: {
                Text("Share 1")
            }
            .activitySheet($item)
            
            Button {
                item = ActivityItem(
                    items: "Button 2: This will be shared"
                )
            } label: {
                Text("Share 2")
            }
            .activitySheet($item)
        }
}

```

## Expected behavior
ActivityView should point to the Button/View it is attached to.

## Screenshots
![Screen_Shot_2021-09-15_at_10_17_04_PM](https://user-images.githubusercontent.com/189621/133554182-d7741971-11f5-4856-89db-4bb492a4e5d9.png)
![Screen_Shot_2021-09-15_at_10_17_13_PM](https://user-images.githubusercontent.com/189621/133554184-0dbdf73b-1ab4-4082-9c8e-3872fa1bb870.png)

## Additional context
I just want to add that this is amazing piece of work and I love it so far. 
Since I am new to SwiftUI, I haven't been able to figure the issue out myself. I also tried to change the way View is displayed, to may be simply take over the full screen, but that doesn't seem to work on iPad. Please let me know if I can help you in any way.

**Comment by elitecoder** [comment]
@shaps80 Thanks for clarifying! Sorry for wasting your time.

**Comment by shaps80** [comment]
> @shaps80 Thanks for clarifying! Sorry for wasting your time.

@elitecoder never a waste of time to help someone out 👍
