### ISSUE TITLE
ActivityView Display Is Missing Activities on iPad

### ISSUE THREAD

**Issue by delawaremathguy** [SwiftUI-Plus/ActivityView#2]
*Have you read the [Contributing Guidelines](https://github.com/shaps80/.github/blob/master/CONTRIBUTING.md)?*  Yes.

## General Information

 - Project version: ActivityView Package shows 1.1.1
 
 
 - Platform/OS version: iOS 15
 
 
 - IDE version: Xcode 13.2.1
 
 
 - Devices: iPad Air 4
 
 
 - Any related GitHub issues: No.

## Describe the bug
When ActivityView is opened on an iPad (e.g., my iPad Air 4), only the top row of the view appears (and the console messages reflect UIKit-related layout issues).  There are no activities from which to choose.

## Steps to reproduce
1. Locate and download my [ShoppingList15 project](https://github.com/delawaremathguy/ShoppingList15).
2. Comment out the .disabled() modifier at line 132 in ShppingListView.swift so you can test on the simulator.
3. Run the app on an iPad simulator (both portrait and landscape orientations are be in the horizontally-regular size class on an iPad)
4. Add an Item to the shopping list (you must have at least one item to possibly see anything meaningful)
5. Tap the share icon ... the UIActivityViewController opens with only a header and no activities from which to select.

## Expected behavior
There should be activities from which to select.

## Stack trace, compiler error, code snippets

There are from the project as now posted on GitHub when run on an iPad 4th generation simulator, with line 132 in ShoppingListView.swift commented-out:

2022-01-02 13:27:43.295107-0500 ShoppingList[18560:939194] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600000910280 V:|-(0)-[_UIActivityContentCollectionView:0x7f8c21031a00]   (active, names: '|':UIView:0x7f8c20247920 )>",
    "<NSLayoutConstraint:0x600000910320 _UIActivityContentCollectionView:0x7f8c21031a00.bottom == UIView:0x7f8c20247920.bottom   (active)>",
    "<NSLayoutConstraint:0x60000091c0f0 'UIView-bottom-readableContentGuide-constraint' UILayoutGuide:0x6000013cdc00'UIViewLayoutMarginsGuide'.bottom == UILayoutGuide:0x6000013cdb20'UIViewReadableContentGuide'.bottom   (active)>",
    "<NSLayoutConstraint:0x60000091fa20 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x6000013cdc00'UIViewLayoutMarginsGuide']-(21)-|   (active, names: '|':_UIActivityContentCollectionView:0x7f8c21031a00 )>",
    "<NSLayoutConstraint:0x60000091d720 'UIView-Encapsulated-Layout-Height' UIView:0x7f8c20247920.height == 72   (active)>",
    "<NSLayoutConstraint:0x60000091fde0 'UIView-top-readableContentGuide-constraint' UILayoutGuide:0x6000013cdb20'UIViewReadableContentGuide'.top == UILayoutGuide:0x6000013cdc00'UIViewLayoutMarginsGuide'.top   (active)>",
    "<NSLayoutConstraint:0x60000091f430 'UIView-topMargin-guide-constraint' V:|-(80)-[UILayoutGuide:0x6000013cdc00'UIViewLayoutMarginsGuide']   (active, names: '|':_UIActivityContentCollectionView:0x7f8c21031a00 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x60000091c0f0 'UIView-bottom-readableContentGuide-constraint' UILayoutGuide:0x6000013cdc00'UIViewLayoutMarginsGuide'.bottom == UILayoutGuide:0x6000013cdb20'UIViewReadableContentGuide'.bottom   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2022-01-02 13:27:43.299232-0500 ShoppingList[18560:939194] [LayoutConstraints] Changing the translatesAutoresizingMaskIntoConstraints property of a UICollectionReusableView that is managed by a UICollectionView is not supported, and will result in incorrect self-sizing. View: <_UIActivityContentFooterView: 0x7f8c20055460; baseClass = UICollectionReusableView; frame = (16 252; 343 52); layer = <CALayer: 0x600002a741e0>>

## Screenshots
*If applicable, add screenshots, gifs, or videos to help explain your problem.*
<img width="854" alt="Screen Shot 2022-01-02 at 1 30 20 PM" src="https://user-images.githubusercontent.com/62509027/147885740-9114df01-9a4d-43a7-9321-09da9381573c.png">

## Additional context
There is no problem when you are in a a horizontally-compact presentation.  ActivityView works fine on an iPhone and when the iPad has a split-screen mode in which ShoppingList lives in a horizontally-compact view.

**Comment by shaps80** [comment]
I've encountered this recently myself but I'm not sure if its a SwiftUI bug specific perhaps to iOs 15 cause its popped up fairly recently.

**Comment by delawaremathguy** [comment]
thanks for your reply.  I think I agree (as of iPadOS 15.2).  

ActivityView looks and works great on an iPhone, but either AV doesn't work as I described on an iPad in a horizontally regular presentation, or it takes over the whole available screen real estate (possibly intentional) when in split view and it is in a horizontally compact presentation.

it could also be based on the ActivityItem supplied, which sounds a little strange ... another developer I consult with is using AV in his app and does not experience the problem I described when using it on his iPad, but his items are a PDF (data) and a URL.

I will continue to monitor and perhaps try a test with something other than text as the only ActivityItem.

regards,
DMG

**Comment by shaps80** [comment]
Yeah I have noticed its def more prevalent on specific iPad sizes. I'm also wondering if its to do with the source view actually, I will investigate soon-ish and try and find a solution. Thanks again for feeding back 👍

**Comment by delawaremathguy** [comment]
hi,

my conclusion: it matters where you place the .activitySheet() modifier.  ShoppingList is fine if the modifier is placed on the button in the navigation bar that invokes the UIActivityViewController, rather than the main view.  (on the iPhone, UIActivityViewController doesn't need this view for presentation.)

**Comment by shaps80** [comment]
Oh yeah that makes sense though because the placement of the modifier defines the `sourceView` as well as the `sourceBounds`. I wonder if that's the issue I have as well, will verify once I've had a minute to test 👍
