### ISSUE TITLE
alternative initialization of Activity(items: ...)

### ISSUE THREAD

**Issue by delawaremathguy** [SwiftUI-Plus/ActivityView#3]
*Have you read the [Contributing Guidelines](https://github.com/shaps80/.github/blob/master/CONTRIBUTING.md)?*
Yes.

## Describe the feature
*Clearly and concisely describe what you would like to add.*
UIActivityViewController accepts an argument of type `[Any]` so it would be nice to carry that forward here.  In my case, i'd like to list several PDFs for printing all at once.

## Is your feature request related to a problem? 
*Clearly and concisely describe the problem.*
No.

## Proposed solution
*Clearly and concisely describe the solution you'd like to see. Include implementation details, if possible.*
I suggest adding the following `init()` to `ActivityItem`.

```
		/// The
		/// - Parameters:
		///   - items: The array of items to share via a `UIActivityViewController`
		///   - activities: Custom activities you want to include in the sheet
	public init(items: [Any], activities: [UIActivity] = [], excludedTypes: [UIActivity.ActivityType] = []) {
		self.items = items
		self.activities = activities
		self.excludedTypes = excludedTypes
	}
```
## Alternatives considered
*Clearly and concisely describe any alternative solutions or features you've considered.*
None.  The current implementation accepts only variadic parameters and not an array.

## Additional context
*Add any other context or screenshots about the feature request here.*
None.

**Comment by shaps80** [comment]
Yep, makes sense. Feel free to open a PR 👍

**Comment by shaps80** [comment]
Closing as per https://github.com/SwiftUI-Plus/ActivityView/pull/4#issuecomment-1063114330
